### PR TITLE
Fix output item deletion bug

### PR DESCRIPTION
**Pull request by xanderstuff**
Discussed in the debuggy discord
note: I didn't test this.... this should get tested before merging

### CODE REVIEW

**Comment by xanderstuff** [comment]
@woodiertexas wanted me to put this in the complete_recipes branch instead :man_shrugging:

**Comment by woodiertexas** [comment]
> @woodiertexas wanted me to put this in the complete_recipes branch instead 🤷‍♂️

Well, the reason was that "complete_recipes" has changes not found in the base 1.19 branch so it made sense for this PR to make a change to code in "complete_recipes".

**Comment by woodiertexas** [comment]
Update: was tested as shown here: https://user-images.githubusercontent.com/17211100/199408113-3ad67791-fa1c-4e13-91cd-c2f731556acb.mp4

**Comment by woodiertexas** [comment]
What the tablesaw did before this PR: https://user-images.githubusercontent.com/17211100/199408469-1ec9a9c8-22a1-41f0-a540-e9eb70c9fc86.mp4

**Comment by xanderstuff** [comment]
excellent!

**Pull request merged**
