### PR TITLE
Complete the vanilla recipes for the tablesaw + bug fixes and quilt dependency update

### PR DESCRIPTION
**Pull request by woodiertexas**

### CODE REVIEW

**Review by falkreon — APPROVED** [review]
:white_check_mark: Fixes my 5:1 fence mistake and fits the data schema well.

**Review by KirboSoftware — APPROVED** [review]
looks good to me

**Comment by falkreon** [comment]
merging this fixes #7

**Review by violet-sh — APPROVED** [review]
LGTM

**Pull request merged**
